version: "3"

services:
  mc:
    image: itzg/minecraft-server:java17-alpine
    ports:
      - 25565:25565
    environment:
      EULA: "TRUE"
      TYPE: "FORGE"
      VERSION: "1.18.2"
      FORGE_VERSION: "40.2.0"
    tty: true
    stdin_open: true
    restart: unless-stopped
    volumes:
      # attach a directory relative to the directory containing this compose file
      - ./Minecraft-Data:/data